### ISSUE TITLE
Add pre-release version number support

### ISSUE THREAD

**Issue by estebanborai** [estebanborai/semantic-version-comparison#1]
Add support to manage a `Pre-Release` member in the version number following [semver](https://semver.org/) specifications

**Comment by sowmiyamuthuraman** [comment]
shall I work on this?

**Comment by estebanborai** [comment]
Hey @sowmiyamuthuraman, you could!
Are you up to do it?

Thanks in advance!

**Comment by estebanborai** [comment]
Resolved
