### ISSUE TITLE
Reimplement functions a "Receiver function" for `Version` struct

### ISSUE THREAD

**Issue by estebanborai** [estebanborai/semantic-version-comparison#3]
Some of the functions implemented in `semvercomp.go` could be implemented as `Receiver Function` due to a context.

Eg:
Instead of doing:
```go
ver := semvercomp.Version{
	Major: 3,
	Minor: 9,
	Patch: 0,
}

var versionString string = semvercomp.String(ver)

fmt.Println(versionString) // "3.9.0"
```

We could simply call a method from the `Version` struct as follows:
```go
ver := semvercomp.Version{
	Major: 3,
	Minor: 9,
	Patch: 0,
}

var versionString string = ver.String()

fmt.Println(versionString) // "3.9.0"
```

[Receiver Funcition](http://www.golangbootcamp.com/book/methods)

**Comment by sowmiyamuthuraman** [comment]
Hey! can I work on this?

**Comment by estebanborai** [comment]
@sowmiyamuthuraman sure!
I will assign it to you!
Remember to update the tests and have fun!
