### ISSUE TITLE
Add validation capabilities

### ISSUE THREAD

**Issue by estebanborai** [estebanborai/semantic-version-comparison#4]
Add capability to validate a version string using RegExp.
The following regexp:
```
(v)?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```
Validates semantic versioning members, this regexp can help in multiple features:
1. Check if a **semantic version** string is valid
2. Adds capability to extract "build data" and "pre-release" data from the **semantic version** string.

**Comment by sowmiyamuthuraman** [comment]
can I work on this?

**Comment by estebanborai** [comment]
Hey @sowmiyamuthuraman, sure! I already have a branch for this issue, you could update your fork and use it!

`task/#4` is the name of the branch.

The target is to return an error when creating a `Version` object with an invalid string.
You could use `fmt.Errorf("The provided tag (%s) is invalid", userTag)`.

I will assign the issue to you, thanks again for your interest, have fun!

**Comment by sowmiyamuthuraman** [comment]
Hi @estebanborai,I noticed that in the commit  1030173 some  of the tests are failing due to the change in the regex.
Example the test for the cleanVersionString fails for the version "v1.0.0"

**Comment by estebanborai** [comment]
Hey @sowmiyamuthuraman, yes! It is because the branch it's not done yet, I added the RegExp and then commited, the task still undone and tests are not updated at the moment

**Comment by sowmiyamuthuraman** [comment]
@estebanborai semver regex matches all the alphabets in place of v.(Eg) `A2.3.0` string is also matched.
